src/celery_demo/celery_demo/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include


def index(request):
    return render(request, template_name="index.html")


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("math/", include("math_demo.urls", namespace="math")),
    path("notify/", include("notification.urls", namespace="notify"))
    # path("notification/", include("notification.urls", namespace="notify")),
]

src/celery_demo/math_demo/urls.py
from django.urls import path

from .views import *
from .apps import MathDemoConfig


app_name = MathDemoConfig.name

urlpatterns = [
    path("", main_page, name="main-page"),
    path("result/<str:task_id>", result_view, name="math-result"),
    path("add/", add_task_view, name="add-request"),
    path("sub/", sub_task_view, name="sub-request"),
    path("mul/", mul_task_view, name="mul-request"),
    path("divide/", divide_task_view, name="divide-request"),
    path("xsum/", xsum_task_view, name="xsum-request"),
]

src/celery_demo/notification/urls.py
from django.urls import path

from .views import send_notification_view, notify_result_view
from .apps import NotificationConfig


app_name = NotificationConfig.name

urlpatterns = [
    path("", send_notification_view, name="send"),
    path("<str:task_id>", notify_result_view, name="result")
]

src/celery_demo/math_demo/models.py
from django.db import models

# Create your models here.

src/celery_demo/notification/models.py
from django.db import models

# Create your models here.

src/celery_demo/pictures/models.py
from django.db import models

# Create your models here.

src/celery_demo/weather/models.py
from django.db import models

# Create your models here.

src/celery_demo/math_demo/views.py
from loguru import logger
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST, require_GET

from libs.logging import LoggerContext
from libs.tasks import get_task_result
from .tasks import (
    add_request, sub_request, mul_request, divide_request, xsum_request
)


__all__ = [
    "add_task_view", "sub_task_view", "mul_task_view", "divide_task_view",
    "xsum_task_view", "main_page", "result_view"
]


@require_GET
@LoggerContext.decorate
def main_page(request):
    logger.info("Hello there!")
    return render(request, template_name="math/index.html")


def _extract_x_and_y(request):
    return int(request.POST["x"]), int(request.POST["y"])


@require_POST
def add_task_view(request):
    x, y = _extract_x_and_y(request)
    result = add_request.delay(x, y)

    return redirect("math:math-result", task_id=result.id)


@require_POST
def sub_task_view(request):
    x, y = _extract_x_and_y(request)
    result = sub_request.delay(x, y)

    return redirect("math:math-result", task_id=result.id)


@require_POST
def mul_task_view(request):
    x, y = _extract_x_and_y(request)
    result = mul_request.delay(x, y)

    return redirect("math:math-result", task_id=result.id)


@require_POST
def divide_task_view(request):
    x, y = _extract_x_and_y(request)
    result = divide_request.delay(x, y)

    return redirect("math:math-result", task_id=result.id)


@require_POST
def xsum_task_view(request):
    numbers = request.POST["numbers"].split()
    result = xsum_request.delay(numbers)

    return redirect("math:math-result", task_id=result.id)


@require_GET
def result_view(request, task_id):
    task_result = get_task_result(task_id)

    return render(request, "result.html", context=task_result)

src/celery_demo/notification/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST, require_GET

from libs.tasks import get_task_result
from .tasks import notify_user_in_slack


__all__ = ["send_notification_view", "notify_result_view"]


@require_POST
def send_notification_view(request):
    username = request.POST["user"]
    result = notify_user_in_slack.delay(username)
    return redirect("notify:result", task_id=result.id)


@require_GET
def notify_result_view(request, task_id):
    task_result = get_task_result(task_id)

    return render(request, "result.html", context=task_result)

src/celery_demo/pictures/views.py
from django.shortcuts import render

# Create your views here.

src/celery_demo/weather/views.py
from django.shortcuts import render

# Create your views here.

src/celery_demo/math_demo/templates/math/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Celery demo math tasks</title>
  <style>
    li {
      margin: 1rem;
    }
  </style>
</head>
<body>
<h2>Page to demonstration math tasks</h2>

<ul>
  <li>
    <h4>Addition task</h4>
    <form action="{% url 'math:add-request' %}" method="post">
      {% csrf_token %}
      <input name="x" type="number"/> + <input name="y" type="number"/>
      <button>Calculate</button>
    </form>
  </li>

  <li>
    <h4>Subtraction task</h4>
    <form action="{% url 'math:sub-request' %}" method="post">
      {% csrf_token %}
      <input name="x" type="number"/> - <input name="y" type="number"/>
      <button>Calculate</button>
    </form>
  </li>

  <li>
    <h4>Multiplication task</h4>
    <form action="{% url 'math:mul-request' %}" method="post">
      {% csrf_token %}
      <input name="x" type="number"/> * <input name="y" type="number"/>
      <button>Calculate</button>
    </form>
  </li>

  <li>
    <h4>Division task</h4>
    <form action="{% url 'math:divide-request' %}" method="post">
      {% csrf_token %}
      <input name="x" type="number"/> / <input name="y" type="number"/>
      <button>Calculate</button>
    </form>
  </li>

  <li>
    <h4>Sum of several numbers task</h4>
    <form action="{% url 'math:xsum-request' %}" method="post">
      {% csrf_token %}
      <input name="numbers" type="text" placeholder="1 2 3 4 5 6"/>
      <button>Calculate</button>
    </form>

  </li>
</ul>

</body>
</html>

src/celery_demo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Celery+Django demo project</title>
</head>
<body>
<ul>
  <li><a href="{% url 'math:main-page' %}">Math demo</a></li>
  <ul>
    <li>
      <a href="#">Get weather</a>
    </li>
    <li>
      <a href="#">Compress image</a>
    </li>
    <li>
      <form action="{% url 'notify:send' %}" method="post">
        {% csrf_token %}
        <input placeholder="Bob" name="user" type="text"/>
        <button>
          Notify
        </button>
      </form>
    </li>
  </ul>
</ul>

</body>
</html>

src/celery_demo/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Sum task result</title>
</head>
<body>
<h2>
  Result of your request
</h2>

{% if task_name %}
  <h3>
    Task name: <span style="color:blue;"><<i>{{ task_name }}</i>></span>
  </h3>

  {% if not status %}
    <p>Task still executing...</p>
  {% else %}
    <p>Result: <b>{{ result }}</b></p>
    <p>Task completed.</p>
  {% endif %}
{% else %}
  <h3 style="color: brown">
    Task not found or celery backend not available.
  </h3>
{% endif %}


</body>
</html>